"""Mini-index generator - writes a compact `SKILLS-INDEX.md`.

This is the Tier 1 of the Two-Tier Discovery architecture (see SPEC §3,
docs/architecture.md). The mini-index gives Claude visibility into what
skills exist (~1k tokens for 80 skills) without the full description
budget. Without it, Claude doesn't know to query skills-radar at all.

Output format: markdown, grouped by hub-tags or scope, one line per skill:
`- skill-name - description (first sentence, ≤80 chars)`
"""

from __future__ import annotations

import logging
from collections import defaultdict
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

DEFAULT_OUTPUT_PATH = Path("~/.claude/SKILLS-INDEX.md").expanduser()


def generate_mini_index(
    skills: list[dict[str, Any]],
    output: Path | None = None,
    *,
    summary_max_chars: int = 80,
    group_by: str = "hub_tags",
) -> Path:
    """Write a mini-index markdown file.

    Args:
        skills: list of skill records from store.list_all() - each is
            {id, metadata, document}.
        output: target path. Defaults to ~/.claude/SKILLS-INDEX.md.
        summary_max_chars: clip first-sentence summary at this length.
        group_by: "hub_tags" (default) or "scope".

    Returns:
        Path written to.
    """
    out_path = (output or DEFAULT_OUTPUT_PATH).expanduser()

    grouped: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for s in skills:
        meta = s.get("metadata", {}) or {}
        if group_by == "hub_tags":
            tags = _csv_to_list(meta.get("hub_tags", ""))
            if tags:
                for t in tags:
                    grouped[t].append(s)
            else:
                grouped["uncategorized"].append(s)
        else:
            scope = meta.get("scope", "unknown")
            top = scope.split(":", 1)[0] if ":" in scope else scope
            grouped[top].append(s)

    lines: list[str] = []
    lines.append("<!-- AUTO-GENERATED by skills-radar - do not edit by hand -->")
    lines.append("# Skills available")
    lines.append("")
    lines.append(
        "Discovery is two-tier: this file is the surface map. To get full "
        "instructions for a skill, call the `load_skill(name)` tool from the "
        "`skills-radar` MCP server. For fuzzy intent, call `search_skills(query)`."
    )
    lines.append("")
    lines.append(f"_Total: {len(skills)} skills indexed._")
    lines.append("")

    for category in sorted(grouped.keys()):
        entries = grouped[category]
        lines.append(f"## {category}")
        lines.append("")
        for entry in sorted(entries, key=lambda e: e.get("id", "")):
            name = entry.get("id", "?")
            meta = entry.get("metadata", {}) or {}
            description = meta.get("description", "") or ""
            summary = _first_sentence(description, summary_max_chars)
            lines.append(f"- **{name}** - {summary}")
        lines.append("")

    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    logger.info(
        "Wrote mini-index (%d skills, %d categories) to %s", len(skills), len(grouped), out_path
    )
    return out_path


def _first_sentence(text: str, max_chars: int) -> str:
    text = text.strip().replace("\n", " ").replace("  ", " ")
    if not text:
        return "-"
    for delim in (". ", ".\n", "! ", "? "):
        idx = text.find(delim)
        if 0 < idx < max_chars:
            text = text[: idx + 1].strip()
            break
    if len(text) > max_chars:
        text = text[: max_chars - 1].rstrip(",.;:- ") + "…"
    return text


def _csv_to_list(s: str) -> list[str]:
    if not s:
        return []
    return [x.strip() for x in s.split(",") if x.strip()]
